### ISSUE TITLE
Repeating Text In Chat, Respawning, and Server Crashing

### ISSUE THREAD

**Issue by Tilier** [tylermurphy534/KenshinsHideAndSeek#21] opened 2022-01-01 18:46 UTC
Sorry to bother you, but I've found some more bugs.

**Describe the bug**
- **Repeating text in chat:** For every game played, the amount of times "Hiders have 30 seconds to hide!" or some countdown message like that is repeated. For instance:
> Once I've played two games, it will say "Hiders have 30 seconds to hide!" twice in chat, after three cames, it'll say it three times, etc.
- **Respawning:** It doesn't happen all the time, but sometimes when I die as a seeker my stuff will drop, I'll be teleported back to the default world, and won't respawn at the map.
- **Server Crashing:** I think this is related to this plugin, I'm not sure - but sometimes, my server will just become unresponsive. I think it happens when you try to start a game sometimes.

**To Reproduce**
**For Repeating Chats:**
play multiple games
**For Respawning:**
I'm not sure what exactly causes it to make the player sometimes respawn correctly and sometimes incorrectly.
**Server Crashing:**
I'm also not exactly sure what causes this, but I think if you keep starting games it might happen at some point.

**Expected behavior**
For the text to not repeat, for the player to respawn in the map and not drop their items, and for the server to not become unresponsive.

**Screenshots**
No screenshots

**System Info (please complete the following information):**
 - OS: Mac
 - Server Host: Minefort
 - MC Version: 1.17
 - Plugin Version: 1.3.3

**Additional context**
Nothing else.

**Comment by tylermurphy534** [comment] 2022-04-09 23:48
Deciding to pick back up this project for a while. I have no idea what is causing the server crashing on your end, did you ever figure this out? What other plugins did you have installed? As for the respawning, I'm currently working on a fix. And finally for the repeating messages, I was unable to reproduce it.

**Comment by tylermurphy534** [comment] 2022-04-12 00:00
Fixed in the 1.4.0 beta. If you are having server crashing issues, i'm assuming your using the /reload command. Please do full restarts instead of doing /reload.

**Closed by tylermurphy534** 2022-04-12 00:00 UTC
